# Generated by Django 4.0 on 2021-12-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedPosition',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('date_open', models.DateField()),
                ('date_close', models.DateField()),
                ('holding', models.IntegerField()),
                ('pl', models.FloatField()),
                ('pl_sgd', models.FloatField()),
                ('pl_per', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalPL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('symbol', models.CharField(max_length=20)),
                ('value_sgd', models.FloatField()),
                ('pl_sgd', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OpenPosition',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('date_open', models.DateField()),
                ('avg_price', models.FloatField()),
                ('total_shares', models.FloatField()),
                ('total_fees', models.FloatField()),
                ('avg_exchange_rate', models.FloatField()),
                ('total_value', models.FloatField()),
                ('total_value_sgd', models.FloatField()),
                ('total_holding', models.IntegerField()),
                ('weightage', models.FloatField()),
                ('unrealised_pl', models.FloatField()),
                ('unrealised_pl_sgd', models.FloatField()),
                ('current_value_sgd', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TickerInfo',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=10)),
                ('sector', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TransacationModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('symbol', models.CharField(max_length=20)),
                ('action', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], max_length=5)),
                ('price', models.FloatField()),
                ('shares', models.FloatField()),
                ('fees', models.FloatField()),
                ('exchange_rate', models.FloatField()),
                ('value', models.FloatField()),
                ('value_sgd', models.FloatField()),
            ],
        ),
    ]
