# Generated by Django 4.0 on 2021-12-19 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openposition',
            old_name='total_shares',
            new_name='total_quantity',
        ),
        migrations.RenameField(
            model_name='transacationmodel',
            old_name='shares',
            new_name='quantity',
        ),
    ]
