# Generated by Django 4.0 on 2021-12-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_closedposition_holding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedposition',
            name='pl',
            field=models.FloatField(db_column='PL'),
        ),
        migrations.AlterField(
            model_name='closedposition',
            name='pl_per',
            field=models.FloatField(db_column='PL_%'),
        ),
        migrations.AlterField(
            model_name='closedposition',
            name='pl_sgd',
            field=models.FloatField(db_column='PL_SGD'),
        ),
    ]
