# Generated by Django 4.0 on 2021-12-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_closedposition_pl_alter_closedposition_pl_per_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickerinfo',
            name='currency',
            field=models.CharField(db_column='CURRENCY', max_length=10),
        ),
        migrations.AlterField(
            model_name='tickerinfo',
            name='industry',
            field=models.CharField(db_column='INDUSTRY', max_length=50),
        ),
        migrations.AlterField(
            model_name='tickerinfo',
            name='name',
            field=models.CharField(db_column='NAME', max_length=50),
        ),
        migrations.AlterField(
            model_name='tickerinfo',
            name='sector',
            field=models.CharField(db_column='SECTOR', max_length=50),
        ),
        migrations.AlterField(
            model_name='tickerinfo',
            name='symbol',
            field=models.CharField(db_column='SYMBOL', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tickerinfo',
            name='type',
            field=models.CharField(db_column='ASSETTYPE', max_length=20),
        ),
    ]
