# Generated by Django 4.0 on 2021-12-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_tickerinfo_type_alter_transactionmodel_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedposition',
            name='date_close',
            field=models.DateField(db_column='DATE_CLOSE'),
        ),
        migrations.AlterField(
            model_name='closedposition',
            name='date_open',
            field=models.DateField(db_column='DATE_OPEN'),
        ),
        migrations.AlterField(
            model_name='closedposition',
            name='holding',
            field=models.IntegerField(db_column='HOLDING_DAY'),
        ),
        migrations.AlterField(
            model_name='closedposition',
            name='pl_per',
            field=models.FloatField(db_column='PL_PERCENTAGE'),
        ),
        migrations.AlterField(
            model_name='closedposition',
            name='symbol',
            field=models.CharField(db_column='SYMBOL', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalpl',
            name='date',
            field=models.DateField(db_column='DATE'),
        ),
        migrations.AlterField(
            model_name='historicalpl',
            name='pl_sgd',
            field=models.FloatField(db_column='PL_SGD'),
        ),
        migrations.AlterField(
            model_name='historicalpl',
            name='symbol',
            field=models.CharField(db_column='SYMBOL', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalpl',
            name='value_sgd',
            field=models.FloatField(db_column='VALUE_SGD'),
        ),
        migrations.AlterField(
            model_name='openposition',
            name='avg_exchange_rate',
            field=models.FloatField(db_column='AVG_EXCHANGE_RATE'),
        ),
        migrations.AlterField(
            model_name='openposition',
            name='avg_price',
            field=models.FloatField(db_column='AVG_PRICE'),
        ),
        migrations.AlterField(
            model_name='openposition',
            name='current_value_sgd',
            field=models.FloatField(db_column='CURRENT_VALUE_SGD'),
        ),
        migrations.AlterField(
            model_name='openposition',
            name='date_open',
            field=models.DateField(db_column='DATE'),
        ),
        migrations.AlterField(
            model_name='openposition',
            name='symbol',
            field=models.CharField(db_column='SYMBOL', max_length=20),
        ),
        migrations.AlterField(
            model_name='openposition',
            name='total_fees',
            field=models.FloatField(db_column='TOTAL_FEES'),
        ),
        migrations.AlterField(
            model_name='openposition',
            name='total_holding',
            field=models.IntegerField(db_column='HOLDING_DAY'),
        ),
        migrations.AlterField(
            model_name='openposition',
            name='total_quantity',
            field=models.FloatField(db_column='TOTAL_QUANTITY'),
        ),
        migrations.AlterField(
            model_name='openposition',
            name='total_value',
            field=models.FloatField(db_column='TOTAL_VALUE'),
        ),
        migrations.AlterField(
            model_name='openposition',
            name='total_value_sgd',
            field=models.FloatField(db_column='TOTAL_VALUE_SGD'),
        ),
        migrations.AlterField(
            model_name='openposition',
            name='unrealised_pl',
            field=models.FloatField(db_column='UNREALISED_PL'),
        ),
        migrations.AlterField(
            model_name='openposition',
            name='unrealised_pl_per',
            field=models.FloatField(db_column='UNREALISED_PL_PERCENTAGE'),
        ),
        migrations.AlterField(
            model_name='openposition',
            name='unrealised_pl_sgd',
            field=models.FloatField(db_column='UNREALISED_PL_SGD'),
        ),
        migrations.AlterField(
            model_name='openposition',
            name='weightage',
            field=models.FloatField(db_column='WEIGHTAGE'),
        ),
    ]
