# Generated by Django 4.0 on 2021-12-21 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_closedposition_date_close_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openposition',
            name='weightage',
        ),
    ]
