# Generated by Django 4.0 on 2021-12-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_openposition_weightage'),
    ]

    operations = [
        migrations.AddField(
            model_name='closedposition',
            name='value_sgd',
            field=models.FloatField(db_column='VALUE_SGD', default=0),
        ),
    ]
