# Generated by Django 4.0 on 2021-12-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_closedposition_value_sgd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closedposition',
            name='value_sgd',
        ),
        migrations.AddField(
            model_name='closedposition',
            name='value_sgd_open',
            field=models.FloatField(db_column='VALUE_SGD_OPEN', default=0),
        ),
    ]
