# Generated by Django 4.0 on 2021-12-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_closedposition_value_sgd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpl',
            name='value_sgd',
        ),
        migrations.RemoveField(
            model_name='openposition',
            name='current_value_sgd',
        ),
        migrations.RemoveField(
            model_name='openposition',
            name='unrealised_pl',
        ),
        migrations.RemoveField(
            model_name='openposition',
            name='unrealised_pl_per',
        ),
        migrations.RemoveField(
            model_name='openposition',
            name='unrealised_pl_sgd',
        ),
        migrations.AddField(
            model_name='historicalpl',
            name='price',
            field=models.FloatField(db_column='PRICE', default=0),
        ),
    ]
