# Generated by Django 4.0 on 2021-12-30 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_historicalpl_value_sgd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openposition',
            name='total_holding',
        ),
    ]
