# Generated by Django 4.0 on 2022-07-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_openposition_total_holding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('date_dividend', models.DateField()),
                ('dividends', models.FloatField()),
                ('total_quantity', models.FloatField()),
                ('total_value_sgd', models.FloatField()),
                ('latest_exchange_rate', models.FloatField()),
                ('dividend_value', models.FloatField()),
                ('dividend_adjusted', models.FloatField()),
                ('dividend_per', models.FloatField()),
            ],
        ),
    ]
