# Generated by Django 4.0 on 2022-08-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_dividend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('symbol', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('current_price', models.FloatField()),
                ('target_price', models.FloatField()),
                ('direction', models.CharField(choices=[('Above', 'Above'), ('Below', 'Below')], max_length=10)),
            ],
        ),
    ]
