# Generated by Django 4.0 on 2022-08-14 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='current_price',
        ),
    ]
