# Generated by Django 4.0 on 2022-09-30 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_watchlist_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpl',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
