# Generated by Django 4.0 on 2022-10-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_historicalpl_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpl',
            name='date',
        ),
        migrations.RemoveField(
            model_name='historicalpl',
            name='pl_sgd',
        ),
        migrations.AddField(
            model_name='historicalpl',
            name='endofweek',
            field=models.DateField(db_column='ENDOFWEEK', default='2020-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalpl',
            name='value',
            field=models.FloatField(db_column='VALUE', default=2020),
            preserve_default=False,
        ),
    ]
