# Generated by Django 4.0 on 2022-10-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_historicalpl_date_remove_historicalpl_pl_sgd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpl',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
