# Generated by Django 4.0 on 2022-10-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_historicalpl_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpl',
            name='pl_per',
            field=models.FloatField(default=0.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalpl',
            name='pl_sgd',
            field=models.FloatField(default=0.5),
            preserve_default=False,
        ),
    ]
