# Generated by Django 4.0 on 2022-10-02 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_historicalpl_pl_per_historicalpl_pl_sgd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpl',
            old_name='pl_per',
            new_name='total_value',
        ),
        migrations.RemoveField(
            model_name='historicalpl',
            name='pl_sgd',
        ),
    ]
